name: Docker stuff
# uses https://github.com/docker/build-push-action

on:
  - push
  # release:
  #   types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      - name: Docker Build and Docker Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # According to https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release `$GITHUB_REF` is going to be the tag of the release
          tags: singlespa/import-map-deployer:${env.BRANCH_NAME},singlespa/import-map-deployer:latest
